# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# 某个网站抓取
- type: subscribe
  options:
    url: https://uploader.shimo.im/f/PrNQFUgdGxxERxYz.txt 
# 某个网站抓取
- type: subscribe
  options:
    url: https://pp.xbin.xyz/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://uploader.shimo.im/f/PQbNhl0t1OkmyFD2.txt
# 某个网站抓取
- type: subscribe
  options:
    url: https://uploader.shimo.im/f/kg40R2Txc2e8ghgi.txt

# 某个网站抓取
- type: subscribe
  options:
    url: https://tg.moneyfly.club/ss/sub 
# 某个网站抓取
- type: subscribe
  options:
    url: https://tg.moneyfly.club/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://tg.moneyfly.club/ssr/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://tg.moneyfly.club/vmess/sub

# 某个网站抓取
- type: subscribe
  options:
    url: http://45.154.14.111/sip002/sub

# 某个网站抓取
- type: subscribe
  options:
    url: https://tg.moneyfly.club/clash/proxies  
# 某个网站抓取
- type: subscribe
  options:
    url: https://d.zaix.ru/nELe.txt
# 某个网站抓取
- type: subscribe
  options:
    url: https://d.zaix.ru/nELf.txt
# 某个网站抓取
- type: subscribe
  options:
    url: https://d.zaix.ru/nELi.txt 
# 某个网站抓取
- type: subscribe
  options:
    url: https://jiedian.lq01.ml/ssr/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://jiedian.lq01.ml/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://jiedian.lq01.ml/ss/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ss/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ssr/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/vmess/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/trojan/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolss.tk/clash/proxies
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolss.tk/ss/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolss.tk/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolss.tk/ssr/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolss.tk/vmess/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypoolss.tk/trojan/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://jiedian.lq01.ml/vmess/sub
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrLists
    num: 200    
# tg频道抓取
- type: tgchannel
  options:
    channel: V2List
    num: 200   

# tg频道抓取
- type: tgchannel
  options:
    channel: ShadowsocksRssr
    num: 200  
    
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrGuoup
    num: 200  
    
# tg频道抓取
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200  
    
# tg频道抓取
- type: tgchannel
  options:
    channel: mfssrjd
    num: 200  
    
# tg频道抓取
- type: tgchannel
  options:
    channel: vchfdhvnbn
    num: 200  
    
# 某个网站抓取
- type: subscribe
  options:
    url: https://getyoujinnode.info/rss?type=trojan
    
# 某个网站抓取
- type: subscribe
  options:
    url: https://getyoujinnode.info/rss?type=ssr
    
# 某个网站抓取
- type: subscribe
  options:
    url: https://getyoujinnode.info/rss?type=ss
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-36-1.html
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-49-1.html
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-2-1.html
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://ssrtool.us/tool/free_ssr
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://www.youneed.win/free-v2ray
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://www.youneed.win/free-ssr
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://www.youneed.win/free-ss
    
# 网页模糊抓取
- type: web-fanqiangdang
  options:
    url: https://free-ss.site/
    
# tg频道抓取
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200
    
# tg频道抓取
- type: tgchannel
  options:
    channel: ssList
    num: 200
    
# tg频道抓取
- type: tgchannel
  options:
    channel: yo520
    num: 200
    
# tg频道抓取
- type: tgchannel
  options:
    channel: FlySSR
    num: 200
    
# tg频道抓取
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
    
# tg频道抓取
- type: tgchannel
  options:
    channel: ssList
    num: 200

# 订阅链接
- type: subscribe
  options:
    url: https://github.com/ssrsub/ssr/raw/master/ssrsub
    
# 订阅链接
- type: subscribe
  options:
    url: https://github.com/ssrsub/ssr/raw/master/ss-sub
    
# 订阅链接
- type: subscribe
  options:
    url: https://rss.cnrss.xyz/link/DHBNd9pB9IqHcr7p?mu=2
    
# 订阅链接
- type: subscribe
  options:
    url: https://github.com/ssrsub/ssr/raw/master/v2ray
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/shunfengziyuan/DY-Clash/main/%E5%B0%8F%E7%8C%AB%E5%92%AA%E8%8A%82%E7%82%B91005.yml
    

# tg频道抓取
- type: tgchannel
  options:
    channel: cnhumanright99
    num: 200
    
# 订阅链接
- type: subscribe
  options:
    url: https://starlink.cx/api/v1/client/subscribe?token=4b6d37e4a5a7bb9c263be2c0a31b151c
    
# tg频道抓取
- type: tgchannel
  options:
    channel: Xinana_awsl
    num: 200
    
# 订阅链接
- type: subscribe
  options:
    url: https://jiang.netlify.app
    
# 订阅链接
- type: subscribe
  options:
    url: https://yzzz.ml/freessr
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
    
# 订阅链接
- type: subscribe
  options:
    url: https://shadow-socks-share.herokuapp.com/subscribe
   
# 订阅链接
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=DAYxR3mMaZAsaqUb
    
# 订阅链接
- type: subscribe
  options:
    url: https://qiaomenzhuanfx.netlify.app
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/online
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
   
# 订阅链接
- type: subscribe
  options:
    url: https://youlianboshi.netlify.app
    
# 订阅链接
- type: subscribe
  options:
    url: http://ss.pythonic.life/full/subscribe
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ntkernel/lantern/master/vmess_base64.txt
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://zhuanqianxue.com/post/201.html
    
# 订阅链接
- type: subscribe
  options:
    url: https://gooii.ml/v2ray/sub1
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub

# tg频道抓取
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 200
    
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypool.ga/ss/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypool.ga/ssr/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypool.ga/vmess/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://proxypool.ga/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/ss/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/ssr/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/vmess/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/ss/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/ssr/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/vmess/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://caicai.moose.tk/sip002/sub
# 某个网站抓取
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/money-fly/subaddress/main/ss.txt
# 某个网站抓取
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/money-fly/subaddress/main/ssr.txt
# 某个网站抓取
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/money-fly/subaddress/main/vmess.txt
